version: "3.8"

services:
  db:
    image: postgres:14
    container_name: crypto_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_db
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: crypto_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/crypto_db
    ports:
      - "8000:8000"
